name: esrs_eqa_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.1
  dio: ^5.9.2
  path_provider: ^2.0.15
  open_file: ^3.2.1
  nb_utils: ^7.1.7+2
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  google_fonts: ^8.0.2
  flutter_secure_storage: ^10.0.0
  flutter_dotenv: ^6.0.0
  flutter_vector_icons: ^2.0.0

  # Media packages
  syncfusion_flutter_pdfviewer: ^33.1.45
  video_player: ^2.5.1
  audioplayers: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - images/